// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoI9WlI_w-F6XK4lnAcoVvz52ct3Yhg6U',
    appId: '1:496366939804:web:0adfd143acb2692f48c759',
    messagingSenderId: '496366939804',
    projectId: 'edulycee-66a3a',
    authDomain: 'edulycee-66a3a.firebaseapp.com',
    storageBucket: 'edulycee-66a3a.firebasestorage.app',
    measurementId: 'G-E02407ECWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN-by140aCG6rYLrqo2spQU-buG7x6ozY',
    appId: '1:496366939804:android:0f0cc96b0c55617a48c759',
    messagingSenderId: '496366939804',
    projectId: 'edulycee-66a3a',
    storageBucket: 'edulycee-66a3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSY759K6-_y5zNRJHO40ldgnlMhfyKDxs',
    appId: '1:496366939804:ios:a8d92b2397591fa148c759',
    messagingSenderId: '496366939804',
    projectId: 'edulycee-66a3a',
    storageBucket: 'edulycee-66a3a.firebasestorage.app',
    iosBundleId: 'com.example.scoalr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSY759K6-_y5zNRJHO40ldgnlMhfyKDxs',
    appId: '1:496366939804:ios:a8d92b2397591fa148c759',
    messagingSenderId: '496366939804',
    projectId: 'edulycee-66a3a',
    storageBucket: 'edulycee-66a3a.firebasestorage.app',
    iosBundleId: 'com.example.scoalr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoI9WlI_w-F6XK4lnAcoVvz52ct3Yhg6U',
    appId: '1:496366939804:web:f03ada00e73a240248c759',
    messagingSenderId: '496366939804',
    projectId: 'edulycee-66a3a',
    authDomain: 'edulycee-66a3a.firebaseapp.com',
    storageBucket: 'edulycee-66a3a.firebasestorage.app',
    measurementId: 'G-G344WEXRJP',
  );
}
